### PR TITLE
Fix: allow candles and campfires to trigger gas

### LINKED ISSUE #471: Bug: only ambrosium torches explode gas
### What Feature Types Apply to This Bug?

Block, System

### Other Type

_No response_

### What Type of Bug Is This?

None

### Forge Version

21.1.90

### The Aether II Version

1.21-0.0.1 (Job number 2374)

### Is This Bug a Conflict With Another Mod?

_No response_

### Client Log

_No response_

### Crash Report (if applicable)

_No response_

### Steps to Reproduce

place acid, and then place any fire source: all candles, torch, soul torch, camp fire, soul camp fire, fire, soul fire, outpost camp fire, (debatable: jack o lantern, lava, lava cauldron, flame arrows).

### What You Expect To Happen

fire should cause the gas to explode

### What Actually Happened

only ambrosium torches explode the gas

### Additional Details

(The gas is invisible, but it forms around acid. I confirmed it was there before taking the screenshot.)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

### PR DESCRIPTION
**Pull request by Ultrasquid9**
Allows lit candles and campfires to trigger gas. Unlit ones will not trigger it. This should be relatively simple to expand to include stuff like furnaces as well. 

Fixes #471 

I agree to the Contributor License Agreement (CLA).

### CODE REVIEW

File: src/main/java/com/aetherteam/aetherii/block/natural/GasBlock.java [hunk 1]
```diff
@@ -77,9 +80,8 @@ protected void updateIndirectNeighbourShapes(BlockState state, LevelAccessor lev
         for (Vec3i offset : INDIRECT_NEIGHBOR_OFFSETS) {
             mutablePos.setWithOffset(pos, offset);
             if (level.getBlockState(mutablePos).is(this)) {
-                if (level.getBlockState(mutablePos).is(AetherIITags.Blocks.TRIGGERS_GAS) || state.is(AetherIITags.Blocks.TRIGGERS_GAS)) {
-                    this.explode(level, pos, true);
-                }
+				if (shouldExplode(level.getBlockState(mutablePos)) || shouldExplode(state))
```
Comment (bconlon1) [inline src/main/java/com/aetherteam/aetherii/block/natural/GasBlock.java]: Should use `this.` and this text shouldn't be so indented.

File: src/main/java/com/aetherteam/aetherii/block/natural/GasBlock.java [hunk 2]
```diff
@@ -100,9 +102,9 @@ protected void onPlace(BlockState state, Level level, BlockPos pos, BlockState o
         level.scheduleTick(pos, this, 10);
         for (Direction direction : Direction.values()) {
             BlockPos offsetPos = pos.offset(direction.getUnitVec3i());
-            if (level.getBlockState(offsetPos).is(AetherIITags.Blocks.TRIGGERS_GAS)) {
-                this.explode(level, pos, true);
-            }
+
+			if (shouldExplode(level.getBlockState(offsetPos)))
```
Comment (bconlon1) [inline src/main/java/com/aetherteam/aetherii/block/natural/GasBlock.java]: Should use `this.` and this text shouldn't be so indented.

File: src/main/java/com/aetherteam/aetherii/block/natural/GasBlock.java [hunk 3]
```diff
@@ -117,6 +119,21 @@ public void wasExploded(ServerLevel level, BlockPos pos, Explosion explosion) {
         this.explode(level, pos, true);
     }
 
+	public boolean shouldExplode(BlockState state) {
+		if (!state.is(AetherIITags.Blocks.TRIGGERS_GAS))
```
Comment (bconlon1) [inline src/main/java/com/aetherteam/aetherii/block/natural/GasBlock.java]: This text shouldn't be so indented.

File: src/main/java/com/aetherteam/aetherii/block/natural/GasBlock.java [hunk 4]
```diff
@@ -131,7 +148,7 @@ public void explode(LevelAccessor level, BlockPos pos, boolean playSound) {
                 BlockPos offsetPos = pos.relative(direction);
                 if (level.getBlockState(offsetPos).getBlock() instanceof GasBlock gasBlock) {
                     gasBlock.explode(level, offsetPos, level.getRandom().nextInt(20) == 0);
-                } else if (level.getBlockState(offsetPos).is(AetherIITags.Blocks.TRIGGERS_GAS)) {
+                } else if (shouldExplode(level.getBlockState(offsetPos))) {
```
Comment (bconlon1) [inline src/main/java/com/aetherteam/aetherii/block/natural/GasBlock.java]: Should use `this.`

File: src/main/java/com/aetherteam/aetherii/block/natural/GasBlock.java [hunk 5]
```diff
@@ -141,7 +158,7 @@ public void explode(LevelAccessor level, BlockPos pos, boolean playSound) {
     @Override
     protected BlockState updateShape(BlockState state, LevelReader levelReader, ScheduledTickAccess scheduledTickAccess, BlockPos currentPos, Direction facing, BlockPos facingPos, BlockState facingState, RandomSource randomSource) {
         if (levelReader instanceof Level level) {
-            if (level.getBlockState(facingPos).is(AetherIITags.Blocks.TRIGGERS_GAS) || state.is(AetherIITags.Blocks.TRIGGERS_GAS)) {
+            if (shouldExplode(level.getBlockState(facingPos)) || shouldExplode(state)) {
```
Comment (bconlon1) [inline src/main/java/com/aetherteam/aetherii/block/natural/GasBlock.java]: Should use `this.`

File: src/main/java/com/aetherteam/aetherii/data/generators/tags/AetherIIBlockTagData.java [hunk 6]
```diff
@@ -264,8 +265,14 @@ public void addTags(HolderLookup.Provider provider) {
                 AetherIIBlocks.ARKENIUM_TRAPDOOR.get()).addTags(AetherIITags.Blocks.ICHORITE_DECORATIVE_BLOCKS, AetherIITags.Blocks.MARBLED_ICHORITE_DECORATIVE_BLOCKS);
         this.tag(AetherIITags.Blocks.ACID_INSTANTLY_DESTROYS).addTags(BlockTags.LEAVES, AetherIITags.Blocks.AERCLOUDS);
         this.tag(AetherIITags.Blocks.ACID_QUICKLY_DESTROYS).addTags(BlockTags.DIRT, BlockTags.LOGS, BlockTags.PLANKS);
-        this.tag(AetherIITags.Blocks.ACID_SLOWLY_DESTROYS).addTags(AetherIITags.Blocks.HOLYSTONE, Tags.Blocks.STONES);
+        this.tag(AetherIITags.Blocks.ACID_SLOWLY_DESTROYS).addTags(AetherIITags.Blocks.HOLYSTONE, Tags.Blocks.STONES);
```
Comment (bconlon1) [inline src/main/java/com/aetherteam/aetherii/data/generators/tags/AetherIIBlockTagData.java:268]: This text shouldn't be so indented.

File: src/main/java/com/aetherteam/aetherii/entity/block/HoveringBlockEntity.java [hunk 7]
```diff
@@ -143,8 +145,17 @@ public boolean hurtServer(ServerLevel serverLevel, DamageSource pSource, float p
     }
 
     private void markShouldSettle() {
+		Predicate<BlockPos> findPos = (pos) -> {
```
Comment (bconlon1) [inline src/main/java/com/aetherteam/aetherii/entity/block/HoveringBlockEntity.java]: This text shouldn't be so indented.

**Review by bconlon1 — CHANGES_REQUESTED** [review]
various style critiques

**Review by bconlon1 — APPROVED** [review]
lgtm
